/**
 * Cloudflare Worker entry: the OpenNext-built Next.js app, plus the Workflow that runs long AI jobs
 * (transcription, grading, marking, level samples, question generation). See wrangler.jsonc.
 */
import { WorkflowEntrypoint, type WorkflowEvent, type WorkflowStep } from "cloudflare:workers";
// @ts-expect-error -- generated by `opennextjs-cloudflare build`
import { default as nextHandler } from "./.open-next/worker.js";
import { runJob } from "./src/server/jobs/job-runner";
import { setWorkflowEnv, type CloudflareBindings } from "./src/server/env";

export default {
  fetch: nextHandler.fetch,
} satisfies ExportedHandler<CloudflareBindings>;

type JobParams = { jobId: string };

export class JobWorkflow extends WorkflowEntrypoint<CloudflareBindings & Record<string, unknown>, JobParams> {
  async run(event: WorkflowEvent<JobParams>, step: WorkflowStep) {
    setWorkflowEnv(this.env);
    // Each named job step becomes a durable, retried Workflow step.
    await runJob(event.payload.jobId, (name, fn) =>
      step.do(name, { retries: { limit: 2, delay: "5 seconds", backoff: "exponential" }, timeout: "10 minutes" }, fn as () => Promise<never>),
    );
  }
}
