/**
 * Copy the scoring sections of rubrics/*-writing.md into a TypeScript module, so prompts can use
 * them on Cloudflare Workers (no file system there). Re-run after editing a rubric:
 *
 *   npm run rubrics:sync
 */
import { readFileSync, writeFileSync } from "node:fs";

const section = (md: string, from: string, to: string) => {
  const start = md.indexOf(from);
  const end = md.indexOf(to, start + 1);
  if (start < 0 || end < 0) throw new Error(`Rubric section not found: ${from} … ${to}`);
  return md.slice(start, end).trim();
};

const chi = readFileSync("rubrics/chinese-writing.md", "utf8");
const eng = readFileSync("rubrics/english-writing.md", "utf8");

const out = {
  /** §2–§4: criteria, 品第, caps, 錯別字 rules, level descriptors, distilled level markers */
  CHINESE_SCORING: section(chi, "## 2.", "## 5."),
  /** §4: distilled level markers only (feedback and level samples) */
  CHINESE_LEVEL_MARKERS: section(chi, "## 4.", "## 5."),
  /** §2.4: what counts as 錯別字 */
  CHINESE_WRONG_CHAR_RULES: section(chi, "### 2.4", "## 3."),
  /** §6: 甲部 facts */
  CHINESE_PART_A: section(chi, "## 6.", "## 7."),
  /** §2–§4: domains, descriptors, level markers */
  ENGLISH_SCORING: section(eng, "## 2.", "## 5."),
  ENGLISH_LEVEL_MARKERS: section(eng, "## 4.", "## 5."),
  /** §5: error taxonomy table */
  ENGLISH_ERROR_TAGS: section(eng, "## 5.", "## 6."),
};

const body = Object.entries(out)
  .map(([k, v]) => `export const ${k} = ${JSON.stringify(v)};`)
  .join("\n\n");
writeFileSync(
  "src/server/ai/prompts/writing-rubric-text.ts",
  `// Generated by scripts/sync-writing-rubrics.mts from rubrics/*-writing.md. Do not edit by hand.\n\n${body}\n`,
);
console.log("Wrote src/server/ai/prompts/writing-rubric-text.ts");
