"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { callAi } from "@/features/jobs/local-jobs";
import { api, unwrap, type Ok } from "@/lib/api-client";
import { isLocalMode } from "@/lib/app-mode";
import { qk } from "@/lib/query-keys";
import type { HelperKind } from "@/lib/schemas/writing";
import { topicsFor } from "@/lib/topic-tree";
import * as local from "../lib/local-writing";

type TaskRes = Awaited<ReturnType<(typeof api.writing.tasks)[":questionId"]["$get"]>>;
export type TaskView = Ok<TaskRes>;

const taskKey = (questionId: string) => ["writing", "task", questionId] as const;

/** Task page: question, cached helpers, my submissions on it. Local mode: from this device. */
export function useWritingTask(questionId: string) {
  return useQuery({
    queryKey: taskKey(questionId),
    queryFn: async (): Promise<TaskView> =>
      isLocalMode ? ((await local.getTaskView(questionId)) as TaskView) : unwrap(api.writing.tasks[":questionId"].$get({ param: { questionId } })),
  });
}

/** Ask AI for one helper; the result is cached (server, or this device in local mode) and in the task query. */
export function useAskHelper(questionId: string) {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async (kind: HelperKind): Promise<{ kind: HelperKind; content: unknown; cached: boolean }> =>
      isLocalMode ? local.askHelper(questionId, kind, callAi) : unwrap(api.writing[":questionId"].helpers[":kind"].$post({ param: { questionId, kind } })),
    onSuccess: (res) => {
      qc.setQueryData<TaskView>(taskKey(questionId), (old) => (old ? ({ ...old, helpers: { ...old.helpers, [res.kind]: res.content } } as TaskView) : old));
      qc.setQueryData(qk.helper(questionId, res.kind), res.content);
      if (!res.cached && !isLocalMode) void qc.invalidateQueries({ queryKey: qk.me });
    },
  });
}

export function useOwnPrompt() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async (json: { subject: "chi_writing" | "eng_writing"; part: "A" | "B"; text: string; materials?: string | null; title?: string | null }) =>
      isLocalMode ? local.createOwnPrompt(json) : unwrap(api.writing["own-prompt"].$post({ json })),
    onSuccess: () => {
      if (isLocalMode) void qc.invalidateQueries({ queryKey: ["bank"] });
    },
  });
}

/**
 * A writing task. Cloud: from the bank (free) or newly generated (2 credits, returns a job).
 * Local: always generated by the AI in a job; the task is saved on this device.
 */
export function useNextWritingTask() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async (json: { subject: "chi_writing" | "eng_writing"; topicIds: string[]; part: string; forceNew?: boolean }): Promise<{ questionId?: string; jobId?: string }> => {
      if (isLocalMode) {
        const jobId = await local.createGeneratedTaskJob(json, () => void qc.invalidateQueries({ queryKey: ["bank"] }));
        return { jobId };
      }
      const res = await unwrap(
        api.questions.next.$post({
          json: {
            subject: json.subject,
            kind: "writing_task",
            topicIds: json.topicIds,
            part: json.part,
            language: json.subject === "chi_writing" ? "zh" : "en",
            difficulty: 3,
            extension: false,
            forceNew: json.forceNew ?? false,
          },
        }),
      );
      return res as { questionId?: string; jobId?: string };
    },
    onSuccess: () => {
      if (!isLocalMode) void qc.invalidateQueries({ queryKey: qk.me });
    },
  });
}

export type TopicRow = { id: string; parentId: string | null; kind: string; nameEn: string; nameZh: string };

export function useWritingTopics(subject: "chi_writing" | "eng_writing") {
  return useQuery({
    queryKey: qk.topics(subject),
    queryFn: async () => (isLocalMode ? topicsFor(subject) : ((await unwrap(api.reference.topics.$get({ query: { subject } }))).items as TopicRow[])),
    staleTime: 3600_000,
  });
}
